const express = require('express');
const health = require('./health');
const meals = require('./meals');
const recommendations = require('./recommendations');
const summary = require('./summary');
const chat = require('./chat');
const weather = require('./weather');
const exercises = require('./exercises');
const recipes = require('./recipes');
const supplements = require('./supplements');
const ingredients = require('./ingredients');
const safety = require('./safety');
const trainers = require('./trainers');
const workoutPlans = require('./workoutPlans');
const nutritionists = require('./nutritionists');
const mealPlans = require('./mealPlans');
const coachNotes = require('./coachNotes');
const admin = require('./admin');
const auditLogs = require('./auditLogs');
const roles = require('./roles');
const macroScore = require('./macroScore');
const healthScore = require('./healthScore');
const weeklyPlan = require('./weeklyPlan');
const foodLogs = require('./foodLogs');

const router = express.Router();

router.use('/health', health);
router.use('/meals', meals);
router.use('/recommendations', recommendations);
router.use('/summary', summary);
router.use('/chat', chat);
router.use('/weather', weather);
router.use('/exercises', exercises);
router.use('/recipes', recipes);
router.use('/supplements', supplements);
router.use('/ingredients', ingredients);
router.use('/safety', safety);
router.use('/trainers', trainers);
router.use('/workout-plans', workoutPlans);
router.use('/nutritionists', nutritionists);
router.use('/meal-plans', mealPlans);
router.use('/coach-notes', coachNotes);
router.use('/admin', admin);
router.use('/audit-logs', auditLogs);
router.use('/me/roles', roles);
router.use('/macro-score', macroScore);
router.use('/health-score', healthScore);
router.use('/weekly-plan', weeklyPlan);
router.use('/food-logs', foodLogs);

module.exports = router;
